@api = https://zafirus-c.herokuapp.com

###
GET https://zafirus-c.herokuapp.com/
Content-type: application/json

###
GET https://zafirus-c.herokuapp.com/users
Content-type: application/json

###
GET https://zafirus-c.herokuapp.com/users/62c224aae35b235a0161368d

###
POST https://zafirus-c.herokuapp.com/users
Content-type: application/json

 {
    "name":"Gaston mas",
    "last_name":"Palumbo",
    "phone":"2615033244",
    "certificates":[
    {
        "title":"Angular",
        "description":"Curso en Udemy"
    },
    {
        "title":"React Native",
        "description":"Curso en Platzi"
    }
    ],
    "work_experiences":[
    {
        "type":"programador",
        "id":"5",
        "years_worked":3
    },
    {
        "type":"peluquero",
        "id":"2",
        "years_worked":1
    }
    ],
    "links":{
    "linkedin":"https://www.linkedin.com/in/gastonpalumbo/"
    }
}



###
PUT https://zafirus-c.herokuapp.com/users/62c24aee8a4db0482167c87c
Content-type: application/json

{
    "name":"Aldo GDabriel",
    "last_name":"MaSDrtinez",
    "phone":"2615039594",
    "certificates":[
    {
        "title":"Typescript",
        "description":"Curso en Udemy"
    },
    {
        "title":"NodeJS",
        "description":"Curso en Udemy"
    }
    ],
    "work_experiences":[
    {
        "type":"programador",
        "id":"5",
        "years_worked":7
    },
    {
        "type":"reportero",
        "id":"12",
        "years_worked":2
    },
    {
        "type":"pintor",
        "id":"2",
        "years_worked":2
    }
    ],
    "links":{
    "linkedin":"https://www.linkedin.com/in/martinezaldodev/"
    }
}



###


###
DELETE https://zafirus-c.herokuapp.com/users/62c2249fe35b235a0161368b

