###
GET http://localhost:3001/dashboard/products

###  
POST http://localhost:3001/users
Content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzM0NzA2ZGQxODgzZjM3YzVkODVjNSIsImlhdCI6MTYzNDk0Njg1OCwiZXhwIjoxNjM1MDMzMjU4fQ.MoNZ5HsH40J8YUDnC0cjJAylu6zQt3gjSTZ9jdN-hKc


###
POST http://localhost:3001/users
Content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzM0NzA2ZGQxODgzZjM3YzVkODVjNSIsImlhdCI6MTYzNDk0Njg1OCwiZXhwIjoxNjM1MDMzMjU4fQ.MoNZ5HsH40J8YUDnC0cjJAylu6zQt3gjSTZ9jdN-hKc

{
    "username": "eldiego",
    "email": "eldiego@test.com",
    "roles":[
        "admin",
        "moderator",
        "role3"
    ]
}



###
GET http://localhost:3001/dashboard/product/616642bdeff4e78a5aea2d02

###

GET http://localhost:3001/dashboard/products

###
DELETE http://localhost:3001/dashboard/delete/617271be0bb91a8d3c74be78
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzM0NzA2ZGQxODgzZjM3YzVkODVjNSIsImlhdCI6MTYzNDk0NDg0MywiZXhwIjoxNjM1MDMxMjQzfQ.Zy2LW1xx4bsvKHybpd0OKsfZhvOT65BoSeYRYyukWdk

###
PUT http://localhost:3001/dashboard/product/616e5ba2a2e3f78bdef4e286
Content-type: application/json

{
    "name": "xxxx",
    "description": "xxxx xxxx xxx x xxxx x",
    "price": 111
}