###
GET http://localhost:3001/users
Content-type: application/json

###
GET http://localhost:3001/users/62c2249fe35b235a0161368b

###
POST http://localhost:3001/users
Content-type: application/json

{
    "name":"Aldo Gabriel",
    "last_name":"Martinez",
    "phone":"2615039594",
    "certificates":[
    {
        "title":"Typescript",
        "description":"Curso en Udemy"
    },
    {
        "title":"NodeJS",
        "description":"Curso en Udemy"
    }
    ],
    "work_experiences":[
    {
        "type":"programador",
        "id":"5",
        "years_worked":7
    },
    {
        "type":"reportero",
        "id":"12",
        "years_worked":2
    },
    {
        "type":"pintor",
        "id":"2",
        "years_worked":2
    }
    ],
    "links":{
    "linkedin":"https://www.linkedin.com/in/martinezaldodev/"
    }
}



###
PUT http://localhost:3001/users/62c24aee8a4db0482167c87c
Content-type: application/json

{
    "name":"Aldo GDabriel",
    "last_name":"MaSDrtinez",
    "phone":"2615039594",
    "certificates":[
    {
        "title":"Typescript",
        "description":"Curso en Udemy"
    },
    {
        "title":"NodeJS",
        "description":"Curso en Udemy"
    }
    ],
    "work_experiences":[
    {
        "type":"programador",
        "id":"5",
        "years_worked":7
    },
    {
        "type":"reportero",
        "id":"12",
        "years_worked":2
    },
    {
        "type":"pintor",
        "id":"2",
        "years_worked":2
    }
    ],
    "links":{
    "linkedin":"https://www.linkedin.com/in/martinezaldodev/"
    }
}



###


###
DELETE http://localhost:3001/users/62c2249fe35b235a0161368b

